# -*- coding: utf-8 -*-
"""python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSB6lWsYTaZJVyjRDrtGDrznFluPGVcR
"""

x = 10
x

"""variable is a container to store information and retrieve it later"""

#rules

_mycity="solan"
_mycity

my_sub ="python"
print (my_sub)

#remaining part of variable are letter ,underscore or number
my_sub1 ="science"
my_sub1

#for variable nmaing we can not use number on first position
my_sub1 ="science"
my_sub1

#variable does not use contain space or symbol
my@sub = "machine learning"
my@sub

#Rules for naming variable
#starting position of variable are underscore or later
my_sub ="python"
my_sub

#python are case senstive , variable names such as my_sub,MY_SUB are diff
my_sub="machine learniang"
MY_SUB="deeplearning"
my_sub
MY_SUB

#whaT is keywords
#reserved words in python are known as keywords
import keyword
keyword.kwlist

#data type
#numeric
#integer--absence of decimal point is known as integer
#ex--1,2,3,4
x=1
type(x)#type ()is function that return type of data

#floating point number--presence of decimal
#ex--3.14,7.14
y=7.14
type(y)



#string--data in the form of text
x="solan"
type(x)

b=False
type(b)

#none--it is define null value means nothing
e=None
type(e)

from os import WCOREDUMP
#boolean--it is used to store value in the form oftrue or false
b=WCOREDUMP
type(b)

my_sub="machine learning"
print(my_sub)

my_college ="shoolini university"
type(my_college)

my_sentence='''This is multiple line
sentence ,so thais also a string '''
type(my_sentence)

my_sub="machine learning"
my_sub[8
       ]

my_sub [-16]

my_sub[-15
       ]

my_sub[0]

my_sub[-1]

my_sub="machine learning"
my_sub[0:7:1]
my_sub[8::1]
my_sub[0:15:2]

#method of string

my_sub="PYTHON"
my_sub.lower()

my_sub="machine learning"
my_sub.upper()

my_sub="machine learning"
my_sub.count("a")

mylist=[78,89,34,56]
type(my_list)

mixed_list=["apple",24,3.14,True,None]
type(mixed_list)

my_list=[78,84,36,34]
my_list[0]

my_list=[78,84,36,34]
my_list[-1]

my_list=[2,7,8,4,5,6]
my_list[-1]

my_list=[2,7,8,4,5,6]
my_list[0:5:1]

my_list[0:5]

my_list[0:]

my_list[:5]

my_list[::-1]

my_list[0:5:-1]

#example
my_list=[2,5,8,78,56,456]
sum(my_list)

"""function in list
sum():-this function reyurn addition of the item in list
my_list=[2,7,8,4,3]
"""

#sorted()--this function arrange list in increasing order or decreasing order
my_list=[89,67,45,12,34]
sorted(my_list,reverse=True)

my_list

#apend()--this method aad item end of the list ,item take as argument
list1=[9,8,7,4]
list1.append(100)

#extend ()--this method merge into another list
list1=[9,8,7,4]
list2=[100,200,300]
list1.extend(list2)
list1

#pop()-- this method remove item from the list, and take index as a argument
my_list=[98,87,56,34,100]
my_list.pop(2)

my_list

#reverse()--this method reverse a list
my_list=[98,87,56,52]
my_list.reverse()

my_list



"""dictionary - it is a collection of key and value pair ,every key value pair separated by colon ,the combinations key and a value is known as item ,and every item separated by comma ,enclosed by curly braces"""

my_dict={"name":"abhay","college":"shoolini university"}
type(my_dict)

my_dict={"name":"amit","college":"shoolini"}
my_dict["name"]
my_dict["college"]

my_dict={"name":"amit","college":"shoolini"}
print(my_dict["name"])

print(my_dict["college"])

#keys()--this method find keys of dictionary
my_dict.keys()

list(my_dict.keys())

#values()--this method kind no of value in dictionary
my_dict.values()

list(my_dict.values())

#items()--this method find no of item in dictionary
my_dict.items()

list(my_dict.items())

#get()--this method find value and keys take as argument
my_dict.get("name")

print(my_dict.get("age"))

print(my_dict.get ("age","age is not found"))

#update()--this method update the dictionary and take dictionary as a argument
my_dict.update({"age":"21"})
my_dict

my_dict.update({"name":"jagat"})
my_dict

#zip ()--this function take pair of list as a arguments and return python project
state_list =["hp","up","mp"]
city_list=["shimla","lucknow","bhopal"]
zip(state_list,city_list)

dict(zip(state_list,city_list))

#condition statement
#if--this execute when condition is true
#elif -- this execute when condition is true
#else--this execute when if and elif condition is false
age =input("enter your age")
age=int(input("enter your age"))
if age>60:
  print("you are too old for marry")
elif age<18:
  print("you are too young for marry")
else :
  print("we will find perfect match for you")



"""loop-it helps to run block of code repeatly
loop are two types :
1 . forloop.
2 . whileloop.
a.forloop:- it is work on sequence eg:string,tuple range
b.whileloop:-this loop execute until condition is true

"""

my_sub="python"
print(my_sub[0])
print(my_sub[1])
print(my_sub[2])
print(my_sub[3])
print(my_sub[4])
print(my_sub[5])

for i in range(0,6,1):
 print (i)

for i in range(0,6):
  print(i)

for i in range(6):
      print(i)

my_list= [90,78,65,45]
for i in my_list:
  print(i)

#while loop
i=0#initialization
while i<5:
  print(i)
  i+=1

i=0;
while i<5:
  i+=1
  if  i==3:
    break
  else :
    print(i)

i=0
while i<5:
  i+=1
  if i==3:
    continue
    print(i)
  else:
      print(i)

i=0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
      print(i)

#function :-it performs some operation

#user defined function without argument
def add():
  a=int(input("enter first number:"))
  b=int(input("enter second number:"))
  return a+b

print (add())

#positional argument
def calculation (a,b):
  print("Addition:",a+b)
  print("Subtraction:",a-b)
  print("Multiplication:",a*b)
  print("floor Division:",a//b)
  return "calculation is complete"

print(calculation(10,5))

#default argument
def area_perimeter(width=4,height=8):
  area=width*height
  perimeter=2*(width+height)
  return "Area of rectangle is",area,"and perimeter is",perimeter

print(area_perimeter(5))

#keyword argument
def interst (p,r,t):
  i=(p*r*t)/100
  return i

print (interst(r=10,t=2,p=1000))

#variable length argument :- we give any number of argument
#--1. non-keyword variable length argument. -: it is behave like tuple represent by star(*)
#--2. keyword variable length argument.:- it is behave like dictionary represent by double star(**)

def test(*args):
  print(args)
  print(len(args))
  print(type(args))
test(1,2,3,4,5,6)

test(4,8,9,7,11,8,54,459,)

def sum_number(*args):
  sum=0
  for num in args:
    sum+=num
  return sum

sum_number(789,952,741,963,759,)

# keyword variable length argument
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))

test(a=10,b=20,c=30)

import numpy as np

#one dimensional array
oned_array = np.array([1,2,3])
print(oned_array)

#two dimensional array
twod_array = np.array([[1,2,3],[4,5,6]])
print(twod_array)

row_vector=np.array([[1,2,3]])
print(row_vector)

print(row_vector.transpose())

#ndim --find the dimension
print(row_vector.ndim)

#size ---find number of item
print(row_vector.size)

print(twod_array)

#shape-- find number of row and column in two dimensional array
print(twod_array.shape)

print(row_vector)

print(row_vector.shape)

threed_array = np.random.randint(1,20,(2,3,4))
print(threed_array)

print(threed_array.shape)

import numpy as np
zeros_array=np.zeros((3,3))
print(zeros_array)

import numpy as np
zeros_array=np.zeros((3,3),dtype=int)
print(zeros_array)

import numpy as np
ones_array = np.ones((3,3),dtype=int)
print(ones_array)

import numpy as np
mat1=np.matrix("1,2,3;4,5,6;7,8,9")
print(mat1)

import numpy as np
mat2 = np.random.randint(1,10,(3,3))
print(mat2)

import numpy as np
mat3 =np.random.random((3,3))
print(mat3)

import numpy as np
my_array = np.array([1,2,3,4,5])
print(my_array)
power_array =np.power(my_array,5)
print(power_array)

import numpy as np
my_array=np.array([1,2,3])
print(my_array)
log10_array =np.log10(my_array)

print(log10_array)

#matplotlib
#it is python library
#it is used for data visualization
#how to import
#import matplot pylot as plt

import matplotlib.pyplot as plt
import numpy as np
xpoint =np.array([1,3])
ypoint =np.array([2,4])
plt.plot(xpoint,ypoint)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
cgpa =np.array([6,7,8,9,10])
package=np.array([4,5,6,7,9])
plt.plot(cgpa,package,"*:b",ms=15,mec="red",mfc="orange",linewidth=5)
plt.xlabel("CGPA")
plt.ylabel("package in LPA")
plt.title("abhay personal data")
plt.grid()
plt.show()

#bar plot -- it works on numerical as well as categorical data
import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["apple","banana","orange","watermelon"])
quantity = np.array([100,200,80,70])
color = np.array(["red","yellow","orange","green"])
plt.bar(fruit, quantity ,color=color)
plt.xlabel("fruit")
plt.ylabel("Quantity of fruit")
plt.title("fruit vs fruit quantity")

plt.show()

import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["apple","banana","orange","watermelon"])
quantity = np.array([100,200,80,70])
color = np.array(["red","yellow","orange","green"])
plt.barh(fruit, quantity ,color=color)
plt.ylabel("fruit")
plt.xlabel("Quantity of fruit")
plt.title("fruit vs fruit quantity")

plt.show()

#pie plot
percentage_of_fruit = np.array([20,25,30,45])
fruit = np.array(["apple","banana","orange","watermelon"])
myexplode =np.array([0.2,0,0,0])
plt.pie(percentage_of_fruit,labels=fruit,explode=myexplode)
plt.legend(title ="fruit")
plt.show()

age_of_car = np.array([4,5,6,7,8,9,10,12,14])
speed_of_car = np.array([150,140,120,110,100,90,80,70,60])
# plt.plot(age_of_car,speed_of_car)
plt.scatter(age_of_car,speed_of_car)
plt.xlabel("age of car")
plt.ylabel("speed of car")
plt.title("age of car vs speed of car")
plt.show()

#histogram -- it showing the frequency distribution of the data
x = np.random.randint(40,100,(1,200))
x = x.flatten()
plt.hist(x,bins=20)
plt.xlabel("marks")
plt.ylabel("frequency")
plt.title("marks vs frequency")
plt.show()

print(x)

#pandas--it is python library
#--it is used for data manipulation
#--data structure of pandas 1. series 2. data frame 3.panel
import pandas as pd

my_series = pd.Series(["apple","banana","orange","watermelon"],name="fruit")
(my_series)

df = pd.DataFrame([["apple",250],["banana",70],["orange",80],["watermelon",60]],columns =["fruit","prize"])
df



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
#df = pd.read_csv("")
df = pd.read_csv("/content/imdb_data.csv")
df

# linear regression-- it isvsuperwised algorithm,solved regression based problem.
# there are three type of linear regression
# DEEP LEARNING ---- it is subfield of AI and ML . the structure of deep learning inspired by human brain.
# logical structure-neural network  EX- placement prediction cgpa 10 ,4;iq 100,70;placement 1-placed ,0-not placed

import numpy as np
from numpy.linalg import norm
A = np.array([2,1,2,3,2,9])
B = np.array([3,4,2,4,5,5])
#compute cosine similarity
cosine = np.dot(A,B) / (norm(A) * norm(B))
print("cosine similarity:",cosine)

from transformers import pipeline

summarizer = pipeline("summarization",model="facebook/bart-large-cnn")
from transformers import pipeline


text = """and does so with the correct answer.
If computers were infinitely fast, any correct method for solving a problem
would do. You would probably want your implementation to be within the bounds
of good software engineering practice (for example, your implementation should
be well designed and documented), but you would most often use whichever
method was the easiest to implement.
Of course, computers may be fast, but they are not infinitely fast. And memory
may be inexpensive, but it is not free. Computing time is therefore a bounded
resource, and so is space in memory. You should use these resources wisely, and
algorithms that are efficient in terms of time """


summary = summarizer(text, max_length=30,min_length=10, do_sample=False)
print(summary[0])

#tokenization
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")



text = """and does so with the correct answer.
If computers were infinitely fast, any correct method for solving a problem
would do. You would probably want your implementation to be within the bounds
of good software engineering practice (for example, your implementation should
be well designed and documented), but you would most often use whichever
method was the easiest to implement.
Of course, computers may be fast, but they are not infinitely fast. And memory
may be inexpensive, but it is not free. Computing time is therefore a bounded
resource, and so is space in memory. You should use these resources wisely, and
algorithms that are efficient in terms of time """

from transformers import pipeline
summarizer = pipeline("summarization",model="facebook/bart-large-cnn")

